In [ ]:
city_name="City A"

print(f"City Name: (city_name)")

City Name: (city_name)


In [ ]:
celsius_temp = 25
fahrenheit_temp = (celsius_temp * 9/5) + 32
print(f"{celsius_temp} degrees Celsius is equal to {fahrenheit_temp} degrees Fahrenheit.")

25 degrees Celsius is equal to 77.0 degrees Fahrenheit.


In [ ]:
c_f=500.75

print(f"Carbon Footprint: {c_f} kg CO2")

Carbon Footprint: 500.75 kg CO2


In [ ]:
i_S=c_f<400

print(f"Is the city Sustainable? {i_S}")

Is the city Sustainable? False


In [ ]:
inp = input("Enter a value: ")
result = inp.isdigit() is True
print("Is digit:", result)

Enter a value: 5
Is digit: True


In [ ]:
a = input("Enter first value: ")
b = input("Enter second value: ")

print(a is b)
print(a is not b)

Enter first value: 2
Enter second value: 3
False
True


In [ ]:
my_list = [1, 2, 3, 4, 5]

if 3 not in my_list:
  print("3 is not present in the list")

if 6 not in my_list:
  print("6 is not present in the list")

6 is not present in the list


In [ ]:
num1 = float(input("Enter first number: "))
op = input("Enter operator (+, -, *, /): ")
num2 = float(input("Enter second number: "))

if op == "+":
  result = num1 + num2
elif op == "-":
  result = num1 - num2
elif op == "*":
  result = num1 * num2
elif op == "/":
  result = num1 / num2
else:
  print("Invalid operator")

if op in ("+", "-", "*", "/"):
    print(num1, op, num2, "=", result)

Enter first number: 5
Enter operator (+, -, *, /): +
Enter second number: 3
5.0 + 3.0 = 8.0


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

htt = 26
htc = [city for city in climate_data if city["temperature"] > htt]
print(htc)

# Calculate total footprint and city count for cities above htt
total_footprint = sum(city["carbon_footprint"] for city in htc)
city_count = len(htc)

for city in htc:
    print(f"City: {city['city']}, Temperature: {city['temperature']}°C, Carbon Footprint: {city['carbon_footprint']} kg CO2")

# Calculate average footprint, handling potential division by zero
average_footprint = total_footprint / city_count if city_count else 0
print(f"Average Carbon Footprint for cities above {htt}°C: {average_footprint} kg CO2")

[{'city': 'City B', 'temperature': 30, 'carbon_footprint': 350}, {'city': 'City E', 'temperature': 28, 'carbon_footprint': 450}]
City: City B, Temperature: 30°C, Carbon Footprint: 350 kg CO2
City: City E, Temperature: 28°C, Carbon Footprint: 450 kg CO2
Average Carbon Footprint for cities above 26°C: 400.0 kg CO2


In [ ]:
a = int(input("Enter first value: "))
b = int(input("Enter second value: "))

def add(a, b):
    c = a + b
    return c

result = add(a, b)
print(result)

Enter first value: 3
Enter second value: 3
6


In [ ]:
hpc=max(climate_data, key=lambda x: x['carbon_footprint'])

print(f"The city with the highest carbon footprint is {hpc['city']} with a carbon footprint of {hpc['carbon_footprint']} kg CO2.")


The city with the highest carbon footprint is City C with a carbon footprint of 600 kg CO2.


In [ ]:
e_c=1000
e_f=0.475

def calculate_carbon_footprint(electricity_consumption, emission_factor):
    carbon_footprint = electricity_consumption * emission_factor
    return carbon_footprint

carbon_footprint =  calculate_carbon_footprint(e_c, e_f)

print(f"Carbon Footprint: {carbon_footprint} kg CO2")

Carbon Footprint: 475.0 kg CO2


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

s_t=400
s_c=list(filter(lambda x: x["carbon_footprint"] < s_t, climate_data))

print("Sustainable cities:")
for climate_data in s_c:
  print(climate_data["city"])

Sustainable cities:
City B
City D


In [ ]:
x=lambda a :a +10
print(x(5))

15


In [ ]:
is_leap_year = lambda year: year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
year = int(input("Enter a year: "))
if is_leap_year(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

Enter a year: 2004
2004 is a leap year.


In [ ]:
import pandas as pd

data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

r_S=["Solar","Wind","Hydropower","Geothermal","Biomass"]



In [ ]:
r_S=pd.Series(r_S)

print("Renewable Energy Sources: ")
print(r_S)

Renewable Energy Sources: 
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [ ]:
projects_df=pd.DataFrame(data)

projects_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
projects_df.head(3)

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [ ]:
projects_df.tail(2)

Project  Technology  Capacity (MW)  Cost (Million $) Location  \
3        Solar Roof Z       Solar             50               100   Nevada   
4  Geothermal Plant P  Geothermal            100               250    Idaho   

   Completion Year  
3             2025  
4             2023

In [ ]:
second_and_third_rows = projects_df[1:3]

print(second_and_third_rows)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [ ]:
projects_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [ ]:
high_capacity_projects = projects_df[projects_df["Capacity (MW)"] > 100]

print(high_capacity_projects)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [ ]:
projects_df["Cost per MW"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]
projects_df

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000

In [ ]:
total_capacity=projects_df["Capacity (MW)"].sum()

total_cost=projects_df["Cost (Million $)"].sum()

print(total_capacity)
print(total_cost)

800
1300


In [ ]:
import numpy as np

oda=np.array([1,2,3,4,5])

print(oda)

[1 2 3 4 5]


In [ ]:
two_d_array=np.array([[1,2,3],[4,5,6]])

print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

one_d_array = np.array([10, 20, 30, 40, 50])

print("Array:", one_d_array)
print("Shape:", one_d_array.shape)
print("Number of Dimensions:", one_d_array.ndim)
print("Size:", one_d_array.size)
print("Data Type:", one_d_array.dtype)
print("Item Size:", one_d_array.itemsize)

Array: [10 20 30 40 50]
Shape: (5,)
Number of Dimensions: 1
Size: 5
Data Type: int64
Item Size: 8


In [ ]:
np.random.random(4)


array([0.32868061, 0.00347737, 0.90585283, 0.66163883])

In [ ]:
np.ones(4)


array([1., 1., 1., 1.])

In [ ]:
np.zeros(4)


array([0., 0., 0., 0.])

In [ ]:
array=np.full((3,3),5)

print(array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
identity_array=np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
array1=np.arange(0,10,2)
print(array1)

[0 2 4 6 8]


In [ ]:
linspace_array=np.linspace(0,1,5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
data=np.array([1,2,3,4,5])
print(data[0])
print(data[-1])

1
5


In [ ]:
num_data=np.array([11,22,33,44,55,66,77,88,99])
print(num_data[1:5])
print(num_data[::1])
print(num_data[::-1])

[22 33 44 55]
[11 22 33 44 55 66 77 88 99]
[99 88 77 66 55 44 33 22 11]


In [ ]:
def is_palindrome(text):

    processed_text = ''.join(filter(str.isalnum, text)).lower()
    return processed_text == processed_text[::-1]

input_string = input("Enter a string: ")

if is_palindrome(input_string):
    print(f"'{input_string}' is a palindrome.")
else:
    print(f"'{input_string}' is not a palindrome.")


Enter a string: mayam
'mayam' is a palindrome.


In [ ]:
data=np.array([1,2,3,4,5])

reshaped_data=data.reshape(5,1)

print(reshaped_data)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
import numpy as np

myarray = np.array([[1, 2, 3], [6, 7, 8]])

print(myarray.flatten('F'))

[1 6 2 7 3 8]


In [ ]:
data=[1,4,5,6,7]
mean=np.mean(data)
print(mean)
median=np.median(data)
print(median)
std=np.std(data)
print(std)
variance=np.var(data)
print(variance)


4.6
5.0
2.0591260281974
4.24


In [ ]:
energy_consumption=np.array([100,200,300,400,500])
emission_factor=np

print("Energy Consumption for Different Renewable Sources:")
print(energy_consumption)



Energy Consumption for Different Renewable Sources:
[100 200 300 400 500]
